import React from 'react';
import Head from 'next/head';
import { Container, Typography } from '@mui/material';

const Home = () => {
  return (
    <Container>
      <Head>
        <title>My Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h1" component="h1" gutterBottom>
        Welcome to My Project
      </Typography>
    </Container>
  );
};

export default Home;
